### ISSUE TITLE
Invalid asm.js: Expected numeric literal.

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-utils#17]
Not sure what is causing this when nothing has changed recently in either turtlecoin-utils or turtlecoin-crypto.

```
(node:7794) V8: /media/Downloads/tmp/turtlecoin-wallet-backend-js/node_modules/turtlecoin-utils/lib/crypto.js:5231 Invalid asm.js: Expected numeric literal.
```

To reproduce:

* `git clone https://github.com/turtlecoin/turtlecoin-wallet-backend-js.git`
* `cd turtlecoin-wallet-backend-js`
* `yarn install`
* `yarn test-all`

Output:

```
=== Checking wallet JSON serialization ===
(node:7794) V8: /media/Downloads/tmp/turtlecoin-wallet-backend-js/node_modules/turtlecoin-utils/lib/crypto.js:5231 Invalid asm.js: Expected numeric literal.
 ✔️  Wallet serialization was successful
```

**Comment by zpalmtree** [comment]
Oh, I see. It works fine with `node v10.15.0`, but causes this error with `node v11.11.0`

**Comment by brandonlehmann** [comment]
Node 11 won’t be LTS. 

https://github.com/nodejs/Release

Won’t fix. Sorry :(
