### ISSUE TITLE
Angular import error

### ISSUE THREAD

**Issue by deeterd** [turtlecoin/turtlecoin-utils#33]
Hi guys, i'm trying to import turtlecoin-utils to an angular project and gives me this error.

``
Cannot set property '_d' of undefined
    at BigInteger (biginteger.js:66)
    at Object.<anonymous> (cryptonote.js:35)
``

Possible solution: adding new on line 35 of cryptonote.js file
`const UINT64_MAX = new BigInteger(2).pow(64)`

Thanks

**Comment by brandonlehmann** [comment]
Thanks for the report; however, if you're working with the current master release, please give the development branch a try which is entirely TypeScript based as the legacy JS code will soon be unsupported.

**Comment by deeterd** [comment]
Thank you, I'll try that and let you guys know.

**Comment by brandonlehmann** [comment]
Sorry, meant the 2.x.x branch.

**Comment by deeterd** [comment]
Confirmed. That branch work smoothly.

Thanks
