### ISSUE TITLE
Default Ports point to different servers

### ISSUE THREAD

**Issue by glencjones** [turtlecoin/turtlecoin-utils#47]
using TS 

Basically

w = new WalletAPI(xx,host)
then 
w.open(aa,bb,host).then()

so doing this 
w = new WalletAPI(xx,host,8070)
w.open(aa,bb,host,8070).then()

Seems to work

fails because both apis have different default ports.   forcing the ports gets around this.
But then wallet-apt server SegFaults in /Fee request to deamon .

**Comment by brandonlehmann** [comment]
That’s an invalid use of the API. 

Open is used to open a particular wallet and optionally specifying a different node to use. 

The new statement is for connecting to the wallet-api instance (not the node). 

I’ll check the documentation information as there may be a typo but the use is correct.

**Comment by brandonlehmann** [comment]
There is a typo in the constructor documentation that will be resolved.

**Comment by glencjones** [comment]
I probably should branch and fixit

But dont think thats it

looking at the code

    class WalletAPI extends HTTPClient_1.HTTPClient {
    /**
     * Initializes a new WalletAPI interface
     * @param password the API password for the WalletAPI instance
     * @param host the address of the daemon
     * @param port the port of the daemon
     * @param timeout the timeout to wait for each request in ms
     * @param ssl whether the daemon uses SSL (HTTPS) or not
     * @param userAgent the user agent string to use with requests
     * @param keepAlive whether the underlying HTTP(s) connection should be kept alive and reused
     * @param defaultMixin the default mixin used for generated transactions
     * @param decimalDivisor the decimal divisor to use in converting between atomic units and human readable values
     * @param defaultFeePerByte the default fee per byte to use in generating transactions
     * @param defaultUnlockTime the default unlock time to use in generating transaction
     */
    constructor(password, host, port, timeout, ssl, userAgent, keepAlive, defaultMixin, decimalDivisor, defaultFeePerByte, defaultUnlockTime) {
        super(host, port || 8070, timeout, ssl, userAgent, keepAlive, password, handleError);
        this.m_decimalDivisor = 100;
        this.m_defaultFeePerByte = 1.953125;
        this.m_defaultUnlockTime = 0;
        if (defaultMixin)
            this.m_defaultMixin = defaultMixin;
        if (decimalDivisor)
            this.m_decimalDivisor = decimalDivisor;
        if (defaultFeePerByte)
            this.m_defaultFeePerByte = defaultFeePerByte;
        if (defaultUnlockTime)
            this.m_defaultUnlockTime = defaultUnlockTime;
    }


    later in js



    /**
     * Opens an existing wallet container
     * @param filename the filename of the wallet container
     * @param password the password of the wallet container
     * @param daemonHost the node to use for the wallet container
     * @param daemonPort the node port to use for the wallet container
     * @param daemonSSL whether the node uses SSL or not
     */
    open(filename, password, daemonHost, daemonPort, daemonSSL) {
        return __awaiter(this, void 0, void 0, function* () {
            daemonHost = daemonHost || '127.0.0.1';
            daemonPort = daemonPort || 11898;
            daemonSSL = daemonSSL || false;
            return this.post('wallet/open', { daemonHost, daemonPort, daemonSSL, filename, password });
        });
    }

For wallet they use different ports for the constructor and open hence I get wallets is not open.

If I force the port to be the same it works but then the wallet-api core dumps on fetching fees I think.

Sorry I should branch and help but bust weekend and I have decided to pinch the code out theserver and do what I want in c++

test in TypeScript


import * as tcu from "turtlecoin-utils";

(async (): Promise<void> => {

    let walletd : tcu.WalletAPI = new tcu.WalletAPI('','localhost');

    console.log(walletd);
/*
    walletd.status().then(x => {
        console.log(x.peerCount);
    }, y => {
        console.log(y);
    });
*/

    console.log('Start opening');
    walletd.open( '/home/gjones/wallet', '','localhost').then(x => {
        console.log(x);
    }, y =>  {
        console.log(`error ${y}`);
    });

    console.log(`open ${walletd}`);

    //walletd.alive().then( x => { console.log(x); }, y => { console.log(y); } )

    walletd.balance().then( x => {
        console.log(x);
    }, y => {
        console.log(y);
    }  )

    walletd.close().then();

//    console.log('hello');
})();

MIght be just a bad client 

-*- mode: compilation; default-directory: "~/src/git/scr/crypto/kucoin/turtlewallet/src/" -*-
Compilation started at Fri Jun  4 18:18:51

npm run start

> turtlewallet@1.0.0 start
> node dist/index.js

WalletAPI {
  m_host: 'localhost',
  m_port: 8070,
  m_timeout: 30000,
  m_proto: 'http',
  m_userAgent: 'turtlecoin-utils/3.0.9',
  m_keepAlive: true,
  m_key: 'secret',
  m_errorHandler: [Function: handleError],
  m_agent: Agent {
    _events: [Object: null prototype] {
      free: [Function (anonymous)],
      newListener: [Function: maybeEnableKeylog]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    defaultPort: 80,
    protocol: 'http:',
    options: [Object: null prototype] { keepAlive: true, path: null },
    requests: [Object: null prototype] {},
    sockets: [Object: null prototype] {},
    freeSockets: [Object: null prototype] {},
    keepAliveMsecs: 1000,
    keepAlive: true,
    maxSockets: Infinity,
    maxFreeSockets: 256,
    scheduling: 'lifo',
    maxTotalSockets: Infinity,
    totalSocketCount: 0,
    [Symbol(kCapture)]: false
  },
  m_decimalDivisor: 100,
  m_defaultFeePerByte: 1.953125,
  m_defaultUnlockTime: 0
}
Start opening
open [object Object]
error Error: This operation requires a wallet be open and one has not been opened yet
Error: This operation requires a wallet be open and one has not been opened yet
    at WalletAPI.handleError [as m_errorHandler] (/home/gjones/src/git/scr/crypto/kucoin/turtlewallet/node_modules/turtlecoin-utils/dist/WalletAPI.js:728:26)
    at WalletAPI.<anonymous> (/home/gjones/src/git/scr/crypto/kucoin/turtlewallet/node_modules/turtlecoin-utils/dist/Helpers/HTTPClient.js:108:32)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gjones/src/git/scr/crypto/kucoin/turtlewallet/node_modules/turtlecoin-utils/dist/Helpers/HTTPClient.js:8:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Compilation finished at Fri Jun  4 18:18:53


Like I say if I force the port wallet-api then coredumps, I did start to debug it...for you but have a lot on at the moment.


I'll branch the code, and if I get time I'll have a go at fixing it later, but I assume you'll be quicker.

**Comment by brandonlehmann** [comment]
Please check the generated documentation at: https://utils.turtlecoin.dev/classes/walletapi.html

Your use should be like this:

```typescript
import WalletAPI from 'turtlecoin-utils';

(async () => {
   const walletapi = new WalletAPI('APIPasswordHere', 'localhost or IP of wallet-api service', 8070);

   await walletapi.open('/path/to/a/walletfile.wallet', 'walletpasswordhere', 'localhost or NODE/daemon IP address here', 11898);
})();
```

For example, mine may be:

```typescript
import WalletAPI from 'turtlecoin-utils';

(async () => {
   const walletapi = new WalletAPI('supersecretwalletapipassword', '127.0.0.1', 8070);

   await walletapi.open('/home/brandonlehmann/sample.wallet', 'supersecretwalletpassword', 'node.turtlepay.io', 443, true);
})();
```

It's **important** to see that the constructor ip/host specified with port 8070 is for the **running** wallet-api binary.

The **open** and **import** methods that accept a host/port expect a **daemon or node** (ie. TurtleCoind) and if you don't specify one, it defaults to localhost:11898.

wallet-api is **not** a daemon/node for the network. It is a RESTful wallet interface that must connect to a daemon/node.

**Comment by glencjones** [comment]
Tried await in the first version, but got wallet not open, with the default ports.  as per your example.  I note you have different ports on the calls.  That didn't work for me but I'm not using node.turtlepay.io.

I assumed it was the wallet/open methods are going to different servers ie the node and the other the walletapi.

When I forced both calls to wallet-api on my system that's localhost:8070 then it looks like its starting to work looking at the wallet-api logs.

but it then fails in the wallet-api with a core dump.  trying to get fees.   I downloaded the current source and can confirm that.

I think I checked it was hitting my local node, I'm going to say it's hitting my local node.

**Comment by brandonlehmann** [comment]
> When I forced both calls to wallet-api on my system that's localhost:8070 then it looks like its starting to work looking at the wallet-api logs.

That won't work because the open statement that's passed to the wallet-api instance expects a node to connect to, not another instance of wallet-api.

**Comment by brandonlehmann** [comment]
![image](https://user-images.githubusercontent.com/20562132/120845819-51262d00-c53f-11eb-9d2f-1b071cce394b.png)

**Comment by glencjones** [comment]
i'm thinking my rpc node or something might not be configured properly, hence wallet-api is not working as expected.

**Comment by brandonlehmann** [comment]
If the node/daemon is running on a different system, you likely need to set the bind address: `--rpc-bind-ip 0.0.0.0` otherwise it's only accessible to localhost.

**Comment by glencjones** [comment]
All the same host, my feeling is its the actual turtled not wallet-api, I have probably not opened it up (Configured it as required).   I have a debug version of the turtled and wallet-api.   I'll spend some time and attach gdb to both.   Now I know the above js should work, it looks the same as what I started with.

**Comment by brandonlehmann** [comment]
Sounds good. Not sure that the gdb will make a difference as unless you're seeing a core fault in the node itself it's very likely a simple configuration error and/or the node is not in a "ready" status.

**Comment by glencjones** [comment]
Agreed, I'm only seeing a crash in wallet-api, but that's probably a usage issue.

**Comment by glencjones** [comment]
out of interest this might mean I should RTFM but on my turtle coin deamon I cant see it connet....

TurtleCoind --log-level 9 --fee-amount 1 --p2p-bind-ip 0.0.0.0 --rpc-bind-ip 0.0.0.0 

was the last act of desperation to open it up..

On wallet-api  I got 

 TurtleCoin v1.0.0.2000 ()
 This software is distributed under the General Public License v3.0

 Copyright 2018-2020, The TurtleCoin Developers

 Additional Copyright(s) may apply, please see the included LICENSE file for more information.
 If you did not receive a copy of the LICENSE, please visit:
 https://github.com/turtlecoin/turtlecoin/blob/master/LICENSE


Want documentation on how to use the wallet-api?
See https://turtlecoin.github.io/wallet-api-docs/

The api has been launched on http://127.0.0.1:8070.
Type exit to save and shutdown.
Incoming POST request: /wallet/open
Incoming GET request: /addresses
Client requested to modify a wallet, whilst no wallet is open

Assume client is same as yours.........

Now the only thing I know that is different is I'm using shared libs on the server and wallet api probably if config and usage is correct.

Using Gentoo LInux and the out the box cmake will not work on that linux without removing the static link options.

**Comment by brandonlehmann** [comment]
Can you verify with the node that you can access the node API? ie. `curl http://localhost:11898/info` ?

It appears that the wallet-api instance attempted to open a wallet, but given that it can't pull any addresses, I'm guessing it failed or did not complete.

**Comment by glencjones** [comment]
gjones@alien gjones $ curl http://localhost:11898/info
{"alternateBlockCount":0,"difficulty":6167473818,"explorer":false,"greyPeerlistSize":543,"hashrate":205582460,"height":3643622,"incomingConnections":0,"lastBlockIndex":3643620,"majorVersion":7,"minorVersion":0,"networkHeight":3643622,"outgoingConnections":5,"startTime":1622833695,"supportedHeight":3000000,"synced":true,"transactionsPoolSize":0,"transactionsSize":4701898,"upgradeHeights":[187000,350000,440000,620000,700000,800000,1000000,1200000,1300000,1400000,1600000,1800000,2000000,2200000,2400000,2600000,2800000,3000000,3200000,3400000,3600000,3800000,4000000,4200000,4400000,4600000,4800000,5000000],"version":"1.0.0","whitePeerlistSize":111}gjones@alien gjones $ 


seems to work

**Comment by brandonlehmann** [comment]
Try launching wallet-api w/ `--log-level 4` which will spit out more information when opening the wallet via the API call (like this)

![image](https://user-images.githubusercontent.com/20562132/120851679-27710400-c547-11eb-8114-f6f8f2213752.png)

**Comment by brandonlehmann** [comment]
Oh yeah, and while I'm thinking about it... I see you started your node with a fee-amount of 1, but didn't supply a fee-address. That **may** be causing the parser in wallet-api to fail (I'd have to check the core code).

Remove the `--fee-amount 1` from your TurtleCoind launch parameters and try again.

**Comment by glencjones** [comment]
I only get 

for 4 ang 5 loglevel   also removed fee  no change turtled

jones@alien ~/Desktop/bfg/turtle-violetminer $ trtl-wallet-api -r secret --log-level 5



████████╗██╗  ██╗██████╗ ████████╗██╗    ██████╗ █████╗ █████╗ ██╗███╗   ██╗
╚══██╔══╝██║  ██║██╔══██╗╚══██╔══╝██║    ██╔═══╝██╔═══╝██╔══██╗██║████╗  ██║
   ██║   ██║  ██║██████╔╝   ██║   ██║    ████╗  ██║    ██║  ██║██║██╔██╗ ██║
   ██║   ██║  ██║██╔══██╗   ██║   ██║    ██╔═╝  ██║    ██║  ██║██║██║╚██╗██║
   ██║   ╚█████╔╝██║  ██║   ██║   ██████╗██████╗╚█████╗╚█████╔╝██║██║ ╚████║
   ╚═╝    ╚════╝ ╚═╝  ╚═╝   ╚═╝   ╚═════╝╚═════╝ ╚════╝ ╚════╝ ╚═╝╚═╝  ╚═══╝

 TurtleCoin v1.0.0.2000 ()
 This software is distributed under the General Public License v3.0

 Copyright 2018-2020, The TurtleCoin Developers

 Additional Copyright(s) may apply, please see the included LICENSE file for more information.
 If you did not receive a copy of the LICENSE, please visit:
 https://github.com/turtlecoin/turtlecoin/blob/master/LICENSE


Want documentation on how to use the wallet-api?
See https://turtlecoin.github.io/wallet-api-docs/

The api has been launched on http://127.0.0.1:8070.
Type exit to save and shutdown.
Incoming POST request: /wallet/open
Incoming GET request: /addresses
Client requested to modify a wallet, whilst no wallet is open



Let me hit gdb and put some personal effort in,    my mind is telling me I have linked again version x....  but then when its running I'm probably running with different lib versions. Maybe only a slight version difference maybe but enough to cause issues.

Maybe it's just wallet-api, the turtled has been running for months without issue.

Thanks for the help!  Need to dash,,

**Comment by glencjones** [comment]
Thats why we statically link :)

**Comment by brandonlehmann** [comment]
Roger that. Here if you need further assistance. Or ping me on discord/matrix.

**Comment by glencjones** [comment]
Solved cmake issue, my gentoo box was lacking static libs.  Curl does seem to work.   can you supply the Package,Json file I have a feeling its there at the moment having excluded wallet-api and TurtleCoind

**Comment by brandonlehmann** [comment]
It’s in the repo :)

**Comment by glencjones** [comment]
Excellent
